modLoader = "javafml"
loaderVersion = "[38,)"
license = "All Rights Reserved"
[[mods]]
modId = "hopo"
version = "1.1.5"
displayName = "HopoBetterMineshaft"
credits = ""
authors = "Hoponopono"
description = ""